### ISSUE TITLE
SUB: Create checkbox to show on frontend for posts/reples

### ISSUE THREAD

**Issue by aadityanairaaq** [CMU-17313Q/nodebb-f24-elev8#36]
Link to issue #35 
Acceptance Criteria: The task will be complete when a checkbox is created and displayed on the frontend for both posts and replies. Users must be able to click the anonymous checkbox, and it should function properly.

Dependencies: 
No major dependencies for this sub issue. This will establish base for rest of feature.

Estimated effort: 5 hours. This task involves creating and displaying a checkbox on the frontend for both posts and replies. It should allow users to select the anonymous option, establishing the base for other anonymous posting features. The task should be completed in 1 day.

**Comment by Aya-Abdel-Hamid** [comment]
Done reviewing. Looks good to me.
