### ISSUE TITLE
MAIN: Detection of inappropriate words

### ISSUE THREAD

**Issue by hkkubais** [CMU-17313Q/nodebb-f24-elev8#6]
Description: 
As an instructor, I want the system to automatically detect and flag inappropriate words, so that the community stays respectful and focused.

Justification for Priority:
This feature is essential to maintaining a respectful and safe environment on the platform. Detecting inappropriate language ensures that discussions remain professional and conducive to learning.

Impact:
The implementation of this feature will help foster a healthy, respectful community by automatically identifying and flagging inappropriate language. It will ensure that posts adhere to community guidelines, contributing to a positive user experience.

Effort:
The estimated effort for completing the inappropriate word detection is 10 hours, which includes both backend logic for checking posts against a predefined list of inappropriate words and frontend handling for replacing those words with asterisks. This task has a priority of P2, as it is vital for ensuring the platform remains respectful, but does not block other core functionalities.

Estimated Effort:
The estimated effort for completing the detection of inappropriate words is 10 hours. This includes developing backend logic to check posts against a predefined list of inappropriate words and handling frontend replacement of those words with asterisks. It should take around 2 days to complete.

**Comment by shgxshg** [comment]
The feature has been implemented for sprint 1.
